// GENERATED FILE — do not edit. Source: content/assistant/**/*.md
// Regenerate: pnpm --filter web generate:knowledge

export const knowledge = {
  "pt-BR": {
    "consultoria": "# Consultoria de Dados e IA (B2B)\n\nA consultoria é o carro-chefe da TechTelligence: implementamos plataformas de dados e ambientes de IA para empresas — da estratégia à operação. Projetos típicos: estruturação de plataforma de dados (ingestão, armazenamento, governança), implantação de ambientes de IA (incluindo IA generativa aplicada ao negócio), e a combinação dos dois.\n\nComo funciona: começamos entendendo o cenário e o objetivo de negócio, propomos uma arquitetura e um plano em fases, e trabalhamos junto com o time do cliente. O time traz experiência de projetos em empresas de vários portes e setores (a experiência é do time — não afirmamos que essas empresas são clientes da TechTelligence).\n\nPreço e prazo: dependem do escopo — cada projeto é dimensionado sob medida. O caminho certo é uma conversa no WhatsApp ou pelo formulário de contato para entendermos o caso.\n\nPúblico: empresas (o serviço não é para pessoas físicas — para carreira, veja curso e mentoria).\n",
    "criacao-de-sites": "# Criação de sites e aplicações web\n\nCriamos sites e aplicações web profissionais — o próprio techtelligence.net é um exemplo do nosso trabalho: rápido, bilíngue, seguro e com ótima pontuação de performance.\n\nO que fazemos: sites institucionais, landing pages, blogs com SEO, e aplicações web sob medida (áreas logadas, painéis, integrações). Tecnologia moderna (React/Next.js, infraestrutura em nuvem) com boas práticas de segurança e acessibilidade.\n\nEscopo e valores: dependem do que você precisa — um site institucional é bem diferente de uma aplicação com login e pagamentos. Conte o que você tem em mente no WhatsApp ou no formulário de contato e retornamos com uma proposta.\n\nPúblico: empresas e profissionais que precisam de presença digital de qualidade.\n",
    "curso": "# Curso de transição de carreira para TI (B2C)\n\nO curso é para quem quer migrar para a área de TI sem experiência anterior. Cobrimos trilhas como Dev, Front-end, Back-end, DevOps, Engenharia de Dados, Análise de Dados e Ciência de Dados — com foco no que o mercado realmente contrata, porque nossa consultoria vive esse mercado no dia a dia.\n\nFormato: plataforma online própria (plataforma.techtelligence.net), aulas em vídeo, progresso por aula, conteúdo em português e inglês. O curso está em fase beta com acesso gratuito mediante cadastro.\n\nDiferencial: quem constrói o conteúdo também presta consultoria de Dados e IA para empresas — ensinamos o que vemos o mercado pedir. Alunos que se destacam podem vir a ser convidados para participar de projetos da consultoria (é uma possibilidade, não uma promessa).\n\nNão prometemos emprego nem prazo de recolocação — preparamos você da melhor forma que conseguimos.\n",
    "empresa-faq": "# Sobre a TechTelligence + perguntas frequentes\n\nA TechTelligence é uma empresa brasileira de Dados e IA. Nossa lógica: construímos soluções de Dados e IA para empresas (consultoria), então sabemos exatamente o que o mercado contrata — e usamos esse conhecimento para formar pessoas (curso e mentoria). Também criamos sites e aplicações web.\n\nCanais: WhatsApp (botão no site — resposta mais rápida), formulário de contato em techtelligence.net/contato, e-mail contato@techtelligence.net. Site em português e inglês.\n\nFAQ:\n- \"É curso gratuito?\" — o curso está em beta com acesso gratuito mediante cadastro na plataforma.\n- \"Vocês atendem fora do Brasil?\" — sim, atendemos remotamente; o site e o curso são bilíngues.\n- \"Preciso de faculdade para migrar para TI?\" — não necessariamente; o mercado valoriza habilidade demonstrável. O curso e a mentoria ajudam nesse caminho.\n- \"Quanto custa?\" — valores dependem do serviço e do escopo; a conversa no WhatsApp é o caminho para uma proposta.\n",
    "mentoria": "# Mentoria 1:1 (B2C)\n\nA mentoria é um acompanhamento individual para quem quer conquistar uma vaga em TI ou crescer na carreira. Trabalhamos: estratégia de carreira (para onde ir e como), otimização de LinkedIn e currículo, preparação para entrevistas (técnicas e comportamentais) e desenvolvimento de habilidades.\n\nFormato: sessões 1:1 online, plano personalizado conforme o momento da pessoa — quem está começando do zero, quem está migrando de área, ou quem já está em TI e quer subir de nível.\n\nAgendamento e valores: combinados diretamente na conversa — chame no WhatsApp ou use o formulário de contato. Não prometemos resultado (vaga, promoção ou prazo); prometemos preparação séria e direção clara.\n",
  },
  "en": {
    "consultoria": "# Data & AI Consulting (B2B)\n\nConsulting is TechTelligence's flagship: we implement data platforms and AI environments for companies — from strategy to operations. Typical projects: building a data platform (ingestion, storage, governance), deploying AI environments (including applied generative AI), or both combined.\n\nHow it works: we start by understanding your scenario and business goal, propose an architecture and a phased plan, and work alongside your team. The team brings experience from projects at companies of many sizes and industries (that experience belongs to the team — we do not claim those companies as TechTelligence clients).\n\nPricing and timeline: they depend on scope — every project is sized individually. The right next step is a WhatsApp chat or the contact form so we can understand your case.\n\nAudience: companies (for individual careers, see the course and mentorship).\n",
    "criacao-de-sites": "# Website and web application development\n\nWe build professional websites and web applications — techtelligence.net itself is an example of our work: fast, bilingual, secure, with excellent performance scores.\n\nWhat we do: institutional websites, landing pages, SEO-ready blogs, and custom web applications (logged-in areas, dashboards, integrations). Modern technology (React/Next.js, cloud infrastructure) with solid security and accessibility practices.\n\nScope and pricing: they depend on what you need — an institutional site is very different from an application with login and payments. Tell us what you have in mind on WhatsApp or through the contact form and we'll come back with a proposal.\n\nAudience: companies and professionals who need a high-quality digital presence.\n",
    "curso": "# Career-transition course into IT (B2C)\n\nThe course is for people moving into IT with no prior experience. Tracks include Dev, Front-end, Back-end, DevOps, Data Engineering, Data Analytics and Data Science — focused on what the market actually hires for, because our consulting team lives in that market daily.\n\nFormat: our own online platform (plataforma.techtelligence.net), video lessons, per-lesson progress, content in Portuguese and English. The course is in beta with free access upon sign-up.\n\nDifferentiator: the people who build the content also deliver Data & AI consulting for companies — we teach what we see the market ask for. Standout students may be invited to join consulting projects (a possibility, not a promise).\n\nWe do not promise a job or a placement timeline — we prepare you as well as we possibly can.\n",
    "empresa-faq": "# About TechTelligence + FAQ\n\nTechTelligence is a Brazilian Data & AI company. Our logic: we build Data & AI solutions for companies (consulting), so we know exactly what the market hires for — and we use that knowledge to train people (course and mentorship). We also build websites and web applications.\n\nChannels: WhatsApp (button on the site — fastest reply), contact form at techtelligence.net/en/contact, email contato@techtelligence.net. The site is available in Portuguese and English.\n\nFAQ:\n- \"Is the course free?\" — the course is in beta with free access upon sign-up on the platform.\n- \"Do you work outside Brazil?\" — yes, we work remotely; the site and course are bilingual.\n- \"Do I need a degree to move into IT?\" — not necessarily; the market values demonstrable skill. The course and mentorship help you build that path.\n- \"How much does it cost?\" — pricing depends on the service and scope; a WhatsApp conversation is the way to get a proposal.\n",
    "mentoria": "# 1:1 Mentorship (B2C)\n\nMentorship is individual guidance for landing an IT job or growing your career. We work on: career strategy (where to go and how), LinkedIn and résumé optimization, interview preparation (technical and behavioral) and skill development.\n\nFormat: online 1:1 sessions with a personalized plan for your moment — starting from zero, switching fields, or already in IT and aiming higher.\n\nScheduling and pricing: arranged directly in conversation — message us on WhatsApp or use the contact form. We do not promise outcomes (a job, a promotion or a timeline); we promise serious preparation and clear direction.\n",
  },
} as const;
